### ISSUE TITLE
Wont Save

### ISSUE THREAD

**Issue by bgreen0722** [mathieuhays/Simple-Documentation#11]
I got it to save my first three notes. But it won't save any more than that. I have logged out and back in to admin, cleared cache, and still won't take another input.

**Comment by mathieuhays** [comment]
Sorry for the late response, I haven't received the notification from github. 
I'll have a look. 
I'm currently working on a new version that should prevent that kind of issue altogether.

**Comment by mathieuhays** [comment]
I'm closing this as I don't have enough details to really investigate this deeper.
I haven't manage to reproduce so far.

I did notice an issue when saving an empty note. I'm releasing a fix for that.

Feel free to re-open this issue if you have more details.
Steps to reproduce always go a long way. Especially when they're very detailed.
Check for errors in the browser console and turn WP_DEBUGon if possible.

Thanks
